### ISSUE TITLE
Diffusion DC-AE example errors - AssertionError: fid ref assets/data/fid/imagenet_512_train.npz not existed

### ISSUE THREAD

**Issue by rockerBOO** [mit-han-lab/efficientvit#139]
Using the diffusion DC-AE example for DC-AE is missing a file. Is this part of the repo?

```
$ python diffusion_dc_ae.py
warning: dist not init
Traceback (most recent call last):
  File "/home/rockerboo/code/others/efficientvit/diffusion_dc_ae.py", line 49, in <module>
    main()
  File "/home/rockerboo/code/others/efficientvit/diffusion_dc_ae.py", line 12, in main
    dc_ae_diffusion = DCAE_Diffusion_HF.from_pretrained(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rockerboo/code/others/efficientvit/.venv/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/rockerboo/code/others/efficientvit/.venv/lib/python3.12/site-packages/huggingface_hub/hub_mixin.py", line 570, in from_pretrained
    instance = cls._from_pretrained(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rockerboo/code/others/efficientvit/.venv/lib/python3.12/site-packages/huggingface_hub/hub_mixin.py", line 790, in _from_pretrained
    model = cls(**model_kwargs)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/rockerboo/code/others/efficientvit/efficientvit/diffusion_model_zoo.py", line 68, in __init__
    evaluator = Evaluator(cfg)
                ^^^^^^^^^^^^^^
  File "/home/rockerboo/code/others/efficientvit/efficientvit/diffusioncore/evaluator.py", line 75, in __init__
    assert os.path.exists(self.cfg.fid.ref_path), f"fid ref {self.cfg.fid.ref_path} not existed"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: fid ref assets/data/fid/imagenet_512_train.npz not existed
```

Thank you, interesting work.

**Comment by han-cai** [comment]
Hi rockerBOO,

You can generate this file following the [readme](https://github.com/mit-han-lab/efficientvit/tree/master/applications/dc_ae#README).
1. Download the ImageNet dataset to ~/dataset/imagenet.
2. Generate reference for FID computation:
```bash
torchrun --nnodes 1 --nproc_per_node=8 -m applications.dc_ae.generate_reference \
    dataset=imagenet imagenet.resolution=512 imagenet.image_mean=[0.,0.,0.] imagenet.image_std=[1.,1.,1.] split=train \
    fid.save_path=assets/data/fid/imagenet_512_train.npz
```

Best,
Han

**Comment by rockerBOO** [comment]
Beautiful, it works! Thank you Han and Junyu
