### ISSUE TITLE
An error occurred with ade20k or cityscapes using eval_seg_model.py

### ISSUE THREAD

**Issue by liaochuanlin** [mit-han-lab/efficientvit#22]
/home/aa/miniconda3/envs/efficientvit/bin/python3.10 /home/aa/efficientvit-master/eval_seg_model.py --dataset ade20k --crop_size 512 --model l1 --path /dataset/ade20k/images/validation 
Eval l1 on ade20k: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/aa/efficientvit-master/eval_seg_model.py", line 703, in <module>
    main()
  File "/home/aa/efficientvit-master/eval_seg_model.py", line 699, in main
    print(f"mIoU = {(interaction.sum / union.sum).cpu().mean().item() * 100:.1f}")
ZeroDivisionError: division by zero

Process finished with exit code 1

**Comment by liaochuanlin** [comment]
Hi @han-cai

**Comment by AbhaSinghPathania** [comment]
I am having facing the same issue.
